config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
  }
  resources :users,only: [:show,:index,:edit,:update] do
   resource :relationships, only: [:create, :destroy]
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'users/:id/follow' => 'users#follow',as:'users_follow'
  get 'users/:id/follower' => 'users#follower',as:'users_follower'
  get "search" => "searches#search"

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @word = params[:word]
    
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<h2><%=@range %>s search for "<%=@word %>"</h2>
<div class="col-xs-9">
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <% if @range != "User" %>
        <th>title</th>
        <% else%>
        <th>name</th>
        <% end %>
        <th>option</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <% if @range == "User" %>
    <tbody>
      <% @users.each do |user| %>
       <tr>
         <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
          <td><%= link_to user.name, user_path(user), class: "user_#{user.id}" %></td>
          <td><%= user.introduction %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
          <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>